steps:
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args: 
      - '-c'
      - |
        export _VERSION_TAG=$([ -z "$TAG_NAME" ] && echo "No Tag") &&
        echo VERSION_TAG : $$_VERSION_TAG &&
        export _BUILD_DATETIME=$(date +"%Y-%m-%d %T") &&
        echo Build Time :  $$_BUILD_DATETIME &&
        gcloud run deploy ${_SERVICE_NAME} \
        --image gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA} \
        --region us-central1 \
        --platform managed \
        --allow-unauthenticated \
        --update-env-vars \
        VERSION_HASH=${SHORT_SHA},BUILD_DATETIME=${_BUILD_DATETIME},VERSION_TAG=${_VERSION_TAG}"
