steps:
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}", "."]
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_SERVICE_NAME}"]

  # Set Build Date Time for cloud run service
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args: 
      - '-c'
      - |
        echo Adding build date  
        echo $(date +"%Y-%m-%d %T") 
        export _BUILD_DATETIME=$(date +"%Y-%m-%d %T")
        echo Build Time :  $$_BUILD_DATETIME
        echo $$_BUILD_DATETIME >/workspace/build_datetime.txt

  # Set Tag 
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args: 
      - '-c'
      - |
        echo Previous step Build Time :  $$_BUILD_DATETIME
        export _VERSION_TAG=$([ -z "$TAG_NAME" ] && echo "No Tag")
        echo VERSION_TAG : $$_VERSION_TAG

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--update-env-vars", 
        "VERSION_HASH=${SHORT_SHA},BUILD_DATETIME=$(cat /workspace/build_datetime.txt),VERSION_TAG=${_VERSION_TAG}"
      ]